---
lessonName: Automating the Troubleshooting Chain
lessonId: 21
category: workflows
lessondiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-21/lessondiagram.png
tier: prod
prereqs:
  - 22  # Python
  - 23  # Linux
description: In this lesson, we'll explore the use of some custom Python scripts for doing some automated troubleshooting.
slug: Derick's Troubleshooting Wizardry
tags:
- troubleshooting
- tshoot

blackboxes:
- name: asterisk
  image: antidotelabs/asterisk
  ports: [8088]
- name: netbox
  image: antidotelabs/netbox
  ports: [8000]

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1
- name: vqfx2
  image: antidotelabs/vqfx:snap2
- name: vqfx3
  image: antidotelabs/vqfx:snap3
  
utilities:
- name: linux1
  image: antidotelabs/utility
- name: sipphone
  image: antidotelabs/pjsua-lindsey
  ports: [22]

connections:
- a: vqfx1
  b: vqfx2
- a: vqfx2
  b: vqfx3
- a: vqfx3
  b: vqfx1
- a: vqfx2
  b: sipphone
- a: vqfx1
  b: netbox
- a: vqfx1
  b: asterisk


stages:
  - id: 1
    description: Get the IP Address for a Phone Extension
