---
lessonName: Working with REST APIs
lessonId: 19
category: fundamentals
lessondiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-19/lessondiagram.png
tier: prod
prereqs:
  - 22  # Python
  - 23  # Linux
description: REST APIs are an extremely popular, flexible option for remote programmability of a network device. In this lesson, we'll cover the basics of REST APIs, interact with one in the bash shell as well as Python, and prepare for using them for higher-order workflows in later lessons.
slug: REST APIs
tags:
- rest
- api
- rest api
- programmability

utilities:
- name: linux1
  image: antidotelabs/utility

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1
  ports: [8080]
- name: vqfx2
  image: antidotelabs/vqfx:snap2
  ports: [8080]
- name: vqfx3
  image: antidotelabs/vqfx:snap3
  ports: [8080]

connections:
- a: vqfx1
  b: vqfx2
- a: vqfx2
  b: vqfx3
- a: vqfx3
  b: vqfx1
- a: vqfx1
  b: linux1

stages:
  - id: 1
    description: Your First API Call

  - id: 2
    description: Let's do it with Python!
  # 3:
  #   description: Diving Deep into an API
