---
lessonName: Automating the Troubleshooting Chain
lessonId: 21
category: workflows
lessondiagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/v0.3.2/lessons/lesson-21/lessondiagram.png
tier: prod
prereqs:
  - 22  # Python
  - 23  # Linux
description: In this lesson, we'll explore the use of some custom Python scripts for doing some automated troubleshooting.
slug: Derick's Troubleshooting Wizardry
tags:
- troubleshooting
- tshoot

endpoints:
- name: linux1
  image: antidotelabs/utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: sipphone
  image: antidotelabs/pjsua-lindsey
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: antidotelabs/container-vqfx
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx2
  image: antidotelabs/container-vqfx
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx3
  image: antidotelabs/container-vqfx
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: asterisk
  image: antidotelabs/asterisk
  additionalPorts: [8088]

- name: netbox
  image: antidotelabs/netbox
  additionalPorts: [8000]


connections:
- a: vqfx1
  b: vqfx2
- a: vqfx2
  b: vqfx3
- a: vqfx3
  b: vqfx1
- a: vqfx2
  b: sipphone
- a: vqfx1
  b: netbox
- a: vqfx1
  b: asterisk


stages:
  - id: 1
    description: Get the IP Address for a Phone Extension
