# Runtime container
FROM debian:stable AS runtime

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qy \
 && apt-get upgrade -qy \
 && apt-get install -y \
    bridge-utils \
    qemu-kvm \
    vim \
    procps \
 && rm -rf /var/lib/apt/lists/*


COPY launch.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/launch.sh

ENTRYPOINT ["/usr/local/bin/launch.sh"]
