---
lessonName: Vendor-Neutral Network Configuration with OpenConfig
lessonId: 26
category: tools
tier: ptr
description: "In this lesson, we'll explore OpenConfig - an industry effort to standardize network configuration and telemetry models"
slug: openconfig

endpoints:

- name: linux
  image: antidotelabs/utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx
  image: antidotelabs/vqfx-full:18.1R1.9
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [830]

connections:
- a: vqfx
  b: linux

stages:
  - id: 1
    description: Install Openconfig Yang module on Junos box

  - id: 2
    description: Provision Openconfig using CLI and Netconf

  - id: 3
    description: Custom Yang modules and custom Yang translator

  - id: 4
    description: Custom Yang config provisioning using CLI and Netconf
