---
lessonName: Event-Driven Network Automation with StackStorm
lessonId: 15
category: tools
tier: prod
lessonDiagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/v0.3.2/lessons/lesson-15/lessondiagram.png
lessonVideo: https://www.youtube.com/embed/WhfAqnn2HMM
prereqs:
  - 13  # NAPALM
  - 14  # YAML
  - 16  # Jinja
description: StackStorm is an event-driven automation framework. In this lesson, we'll learn about the basic primitives you'll need to put StackStorm to work for you.
shortDescription: StackStorm
tags:
- event-driven
- event driven automation
- stackstorm
- st2

endpoints:
- name: st2
  image: antidotelabs/stackstorm
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: antidotelabs/vqfx-snap1
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx2
  image: antidotelabs/vqfx-snap2
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx3
  image: antidotelabs/vqfx-snap3
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh

connections:
- a: vqfx1
  b: vqfx2
- a: vqfx2
  b: vqfx3
- a: vqfx3
  b: vqfx1

stages:
  - id: 1
    description: StackStorm CLI and Basic Concepts

  - id: 2
    description: Actions

  - id: 3
    description: Workflows

  - id: 4
    description: Sensors and Triggers

  - id: 5
    description: Rules

  # Removing for now, will move to separate lesson once category restructuring is finished
  # - id: 6
  #   description: Using EDI for Self-Service Automation
  # - id: 7
  #   description: Change approval via Inquiries 
