---
lessonName: Device Specific Template Generation
lessonId: 35
lessonDiagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/v0.3.2/lessons/lesson-35/lessondiagram.png
category: workflows
tier: prod
prereqs:
  - 23  # Linux
  - 14  # Yaml
  - 16  # Jinja2
description: Having the ability to generate device specific configurations from an approved device template can be beneficial especially for new deployments. 
slug: TEMPLATEGEN
tags:
- pyez
- yaml
- jinja2

endpoints:

- name: linux
  image: antidotelabs/utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: antidotelabs/vqfx:snap1
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [830]

- name: vqfx2
  image: antidotelabs/vqfx:snap2
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [830]

stages:
  - id: 1
    description: Skills Review
  - id: 2
    description: Multiple Devices
  - id: 3
    description: Multiple Devices w/ Uplinks
  - id: 4
    description: Push Generated Configs
