---
name: Automated STIG Compliance Validation
slug: stig-automated-compliance
category: workflows
diagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/v0.3.2/lessons/lesson-32/lessondiagram.png
tier: prod
prereqs:
  - napalm-multi-vendor-network-automation
  - jsnapy-network-testing
  - pyez-junos-automation
description: Security Technical Implementation Guides (STIGs) are the configuration standards for United States Department of Defense (DoD) infrastructure. Any network engineer that has experience in running any part of these systems has had to spent countless hours going over infrastructure elements and ensuring they're compliant with these standards. In this lesson, we'll explore two appraoches for automating STIG compliance checks, and saving countless hours of manual data-gathering.
shortDescription: Automated STIG Compliance

tags:
- jsnapy
- napalm
- stig
- pyez

authors:
- name: Matt Oswalt
  link: https://oswalt.dev

endpoints:
- name: linux1
  image: utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: vqfx-snap1
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [830]

stages:
  - description: STIG Compliance Validation with NAPALM
    guideType: markdown
  - description: STIG Compliance Validation with JSNAPy
    guideType: markdown
  - description: STIG Compliance Validation with custom scripts
    guideType: markdown
