---
name: Terraform & Junos
slug: terraform-junos
category: tools
# diagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/v0.3.2/lessons/lesson-31/lessondiagram.png
description: Terraform provides a declarative way of managing resources and now you can experiment with controlling Junos resources through this exciting lesson! 
tier: prod
shortDescription: Terraform
tags:
  - terraform
  - declarative
  - junos

authors:
- name: David Gee
  link: https://dave.dev

endpoints:
- name: terraform1
  image: terraform
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: vqfx-snap1
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh

connections:
- a: vqfx1
  b: vqfx2
- a: vqfx2
  b: vqfx3
- a: vqfx3
  b: vqfx1

stages:
  - description: Declarative Resources for Networking
    guideType: markdown

  - description: Planning the Resource Graph
    guideType: markdown

  - description: Applying the Execution Plan
    guideType: markdown

  - description: Destroying Plans
    guideType: markdown

  - description: Bonus Material
    guideType: markdown
