---
lessonName: Working with Salt
lessonID: 30
category: introductory
topologyType: custom
lessondiagram: https://raw.githubusercontent.com/sudhiram9/antidote/master/lessons/lesson-30/salt.png
tier: local

utilities:
- name: salt1
  image: sudhishna/salt
  sshuser: antidote
  sshpassword: antidotepassword
  ports: [22]

devices:
- name: vqfx1
  image: antidotelabs/vqfxspeedy:snap1
  sshuser: root
  sshpassword: VR-netlab9
  ports: [8080, 830]

connections:
- a: vqfx1
  b: salt1
  subnet: 10.1.0.0/24

stages:
  1:
    description: Salt Master and Minion
    labguide: https://raw.githubusercontent.com/sudhiram9/antidote/master/lessons/lesson-30/stage1/guide.md
    configs:
      vqfx1: https://raw.githubusercontent.com/sudhiram9/antidote/master/lessons/lesson-30/stage1/configs/vqfx1.txt

  2:
    description: Junos Proxy Minions
    labguide: https://raw.githubusercontent.com/sudhiram9/antidote/master/lessons/lesson-30/stage2/guide.md
    configs:
      vqfx1: https://raw.githubusercontent.com/sudhiram9/antidote/master/lessons/lesson-30/stage2/configs/vqfx1.txt

  3:
    description: Executing Junos commands in Salt
    labguide: https://raw.githubusercontent.com/sudhiram9/antidote/master/lessons/lesson-30/stage3/guide.md
    configs:
      vqfx1: https://raw.githubusercontent.com/sudhiram9/antidote/master/lessons/lesson-30/stage3/configs/vqfx1.txt

