---
lessonName: Network Unit Testing with JSNAPY
lessonId: 12
category: tools
lessonDiagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/master/lessons/lesson-12/lessondiagram.png
tier: prod
prereqs:
  - 14  # YAML
  - 23  # Linux
description: Unit testing your network devices is one of the fundamental building blocks to CI/CD for networking. In this lesson, we'll explore the use of an open source tool - JSNAPy - for doing just this with Junos devices.
slug: JSNAPy
tags:
- jsnapy
- test
- unit test
- testing
collection: 1

utilities:
- name: linux1
  image: antidotelabs/utility

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1
- name: vqfx2
  image: antidotelabs/vqfx:snap2
- name: vqfx3
  image: antidotelabs/vqfx:snap3

connections:
- a: vqfx1
  b: vqfx2
- a: vqfx2
  b: vqfx3
- a: vqfx3
  b: vqfx1

stages:
  - id: 1
    description: No BGP config - tests fail

  - id: 2
    description: Correct BGP config - tests pass

