---
lessonName: Juniper Extension Toolkit (JET)
lessonId: 25
category: tools
description: "In this lesson, we'll explore the Juniper Extension Toolkit (JET), which is a powerful set of tools for building applications that work with Junos."
tier: ptr
shortDescription: JET
collection: 1

endpoints:

- name: linux
  image: antidotelabs/utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx
  image: antidotelabs/container-vqfx
  configurationType: napalm-junos
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [830, 1883, 32767]

connections:
- a: vqfx
  b: linux

stages:
  - id: 1
    description: JET rpc/notification configuration

  - id: 2
    description: Receive events from notification service using MQTT client

  - id: 3
    description: IDL compilation and basic GRPC JET testing

  - id: 4
    description: JET Firewall API to create/update firewall filter

  - id: 5
    description: Closed loop automation with JET
